import { StyleSheet } from 'react-native';

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#fdf6ec',
    padding: 16,
  },
  scrollContent: {
    paddingBottom: 20,
  },
  header: {
    fontSize: 22,
    fontWeight: 'bold',
    marginBottom: 16,
    textAlign: 'center',
    color: '#7c5c1e',
  },
  surahItem: {
    padding: 14,
    backgroundColor: '#fffbe6',
    borderRadius: 10,
    marginBottom: 10,
    borderWidth: 1,
    borderColor: '#e0cfa9',
  },
  surahName: {
    fontSize: 18,
    color: '#7c5c1e',
    textAlign: 'right',
  },
  backButton: {
    marginBottom: 12,
    alignSelf: 'flex-start',
    backgroundColor: '#e0cfa9',
    padding: 8,
    borderRadius: 8,
  },
  backButtonText: {
    fontSize: 16,
    color: '#7c5c1e',
  },
  ayahCount: {
    fontSize: 16,
    color: '#7c5c1e',
    textAlign: 'center',
    marginBottom: 16,
    fontWeight: 'bold',
  },
  ayahCard: {
    backgroundColor: '#fff9ef',
    borderRadius: 16,
    padding: 18,
    marginBottom: 16,
    borderWidth: 1.5,
    borderColor: '#e0cfa9',
    shadowColor: '#bfa76f',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.15,
    shadowRadius: 8,
    elevation: 4,
  },
  ayahText: {
    fontSize: 20,
    color: '#2c2c2c',
    textAlign: 'right',
    lineHeight: 32,
    marginBottom: 12,
  },
  audioButton: {
    backgroundColor: '#f8ecd4',
    padding: 8,
    borderRadius: 8,
    alignItems: 'center',
    borderWidth: 1,
    borderColor: '#bfa76f',
    marginRight: 4,
    minWidth: 36,
    minHeight: 36,
    justifyContent: 'center',
  },
  audioButtonText: {
    color: '#7c5c1e',
    fontSize: 14,
    fontWeight: 'bold',
  },
  // Pagination styles
  paginationContainer: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 24,
    paddingVertical: 16,
    backgroundColor: '#fdf6ec',
    borderTopWidth: 1,
    borderTopColor: '#e0cfa9',
  },
  arrowButton: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: '#f8ecd4',
    borderColor: '#bfa76f',
    borderWidth: 1,
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#bfa76f',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 2,
  },
  arrowButtonDisabled: {
    backgroundColor: '#f0f0f0',
    borderColor: '#ccc',
  },
  arrowText: {
    color: '#7c5c1e',
    fontSize: 30,
    fontWeight: 'bold',
    marginTop: -13,
  },
  arrowTextDisabled: {
    color: '#999',
  },
  pageInfoContainer: {
    alignItems: 'center',
  },
  pageInfoText: {
    color: '#7c5c1e',
    fontSize: 16,
    fontWeight: 'bold',
    fontFamily: 'Cochin',
  },
  slider: {
    width: '100%',
    height: 32,
    alignSelf: 'center',
    marginTop: 2,
    marginBottom: 2,
  },
});

export default styles; 