import { StyleSheet } from 'react-native';

const homeScreenStyles = StyleSheet.create({
  safeArea: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'transparent',
  },
  card: {
    backgroundColor: 'rgba(255,249,239,0.98)',
    borderRadius: 28,
    borderWidth: 2.5,
    borderColor: '#bfa76f',
    paddingVertical: 25,
    paddingHorizontal: 22,
    alignItems: 'center',
    shadowColor: '#bfa76f',
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.2,
    shadowRadius: 20,
    elevation: 10,
    marginHorizontal: 16,
    marginVertical: 10,
    width: '90%',
    alignSelf: 'center',
  },
  initialLoadingContainer: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 40,
  },
  logoGlowContainer: {
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 15,
  },
  logoGlow: {
    position: 'absolute',
    width: 115,
    height: 115,
    borderRadius: 58,
    backgroundColor: '#e0cfa9',
    opacity: 0.45,
    shadowColor: '#bfa76f',
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.5,
    shadowRadius: 25,
    elevation: 10,
  },
  logo: {
    width: 100,
    height: 100,
    borderRadius: 28,
    borderWidth: 2,
    borderColor: '#bfa76f',
    backgroundColor: '#f8ecd4',
    zIndex: 2,
  },
  loadingTitle: {
    fontSize: 32,
    fontWeight: 'bold',
    color: '#7c5c1e',
    marginTop: 20,
    textAlign: 'center',
    fontFamily: 'Cochin',
    letterSpacing: 1,
    textShadowColor: '#e0cfa9',
    textShadowOffset: { width: 1, height: 1 },
    textShadowRadius: 2,
  },
  loadingSubtitle: {
    fontSize: 18,
    color: '#bfa76f',
    marginTop: 15,
    textAlign: 'center',
    fontFamily: 'Cochin',
    opacity: 0.95,
  },
  headline: {
    fontSize: 24,
    fontWeight: 'bold',
    color: '#7c5c1e',
    marginBottom: 6,
    textAlign: 'center',
    fontFamily: 'Cochin',
    letterSpacing: 0.5,
    textShadowColor: '#e0cfa9',
    textShadowOffset: { width: 1, height: 1 },
    textShadowRadius: 2,
  },
  subtitle: {
    fontSize: 14,
    color: '#bfa76f',
    marginBottom: 12,
    textAlign: 'center',
    fontFamily: 'Cochin',
    opacity: 0.95,
    paddingHorizontal: 10,
  },
  decorativeDividerContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 18,
    marginTop: 2,
  },
  decorativeDivider: {
    flex: 1,
    height: 2.5,
    backgroundColor: '#bfa76f',
    borderRadius: 2,
    marginHorizontal: 8,
    opacity: 0.8,
  },
  dividerIcon: {
    fontSize: 18,
    color: '#bfa76f',
    marginHorizontal: 2,
    marginTop: -2,
  },
  button: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#7c5c1e',
    borderColor: '#bfa76f',
    borderWidth: 2,
    paddingVertical: 12,
    paddingHorizontal: 28,
    borderRadius: 28,
    marginVertical: 6,
    shadowColor: '#bfa76f',
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.18,
    shadowRadius: 6,
    elevation: 4,
    width: '95%',
    justifyContent: 'center',
  },
  buttonIcon: {
    fontSize: 20,
    marginRight: 10,
    color: '#e0cfa9',
  },
  buttonText: {
    color: '#fff9ef',
    fontSize: 16,
    fontWeight: 'bold',
    letterSpacing: 0.5,
    fontFamily: 'Cochin',
  },
  footer: {
    marginTop: 20,
    fontSize: 12,
    color: '#bfa76f',
    opacity: 0.7,
    fontFamily: 'Cochin',
    textAlign: 'center',
  },
  loadingOverlay: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: 'rgba(248, 236, 212, 0.85)',
    borderRadius: 32,
    justifyContent: 'center',
    alignItems: 'center',
    zIndex: 10,
    flexDirection: 'row',
  },
  loadingText: {
    marginLeft: 12,
    fontSize: 18,
    color: '#7c5c1e',
    fontFamily: 'Cochin',
    fontWeight: 'bold',
  },
});

export default homeScreenStyles; 