import { StyleSheet } from 'react-native';

const qiblaStyles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: '#fdf6ec',
  },
  container: {
    flex: 1,
    backgroundColor: '#fdf6ec',
  },
  header: {
    minHeight: 70,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 14,
    borderBottomWidth: 1,
    borderBottomColor: '#e0cfa9',
    backgroundColor: '#fff9ef',
  },
  iconButton: {
    width: 44,
    height: 44,
    alignItems: 'center',
    justifyContent: 'center',
  },
  headerCopy: {
    alignItems: 'center',
  },
  eyebrow: {
    color: '#bfa76f',
    fontSize: 12,
    fontWeight: '700',
  },
  title: {
    color: '#7c5c1e',
    fontSize: 21,
    fontWeight: '700',
    marginTop: 2,
  },
  centerContent: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 32,
  },
  loadingText: {
    color: '#7c5c1e',
    fontSize: 16,
    marginTop: 18,
    textAlign: 'center',
  },
  errorText: {
    color: '#7c5c1e',
    fontSize: 16,
    lineHeight: 25,
    marginTop: 18,
    textAlign: 'center',
  },
  content: {
    alignItems: 'center',
    paddingHorizontal: 20,
    paddingTop: 20,
    paddingBottom: 28,
  },
  statusBar: {
    width: '100%',
    minHeight: 46,
    flexDirection: 'row-reverse',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    paddingHorizontal: 14,
    borderWidth: 1,
    borderColor: '#e0cfa9',
    borderRadius: 8,
    backgroundColor: '#fff9ef',
  },
  statusBarReady: {
    borderColor: '#79a466',
    backgroundColor: '#e6efe1',
  },
  statusText: {
    color: '#7c5c1e',
    fontSize: 15,
    fontWeight: '600',
    textAlign: 'center',
  },
  statusTextReady: {
    color: '#3f7c4b',
  },
  compassStage: {
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 27,
  },
  compassOuter: {
    width: 282,
    height: 282,
    borderRadius: 141,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: '#e0cfa9',
    backgroundColor: '#f3ead7',
  },
  compassInner: {
    width: 242,
    height: 242,
    borderRadius: 121,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 2,
    borderColor: '#bfa76f',
    backgroundColor: '#fff9ef',
  },
  direction: {
    position: 'absolute',
    color: '#7c5c1e',
    fontSize: 19,
    fontWeight: '700',
  },
  targetMarker: {
    position: 'absolute',
    top: -18,
    width: 44,
    height: 44,
    borderRadius: 22,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#fff9ef',
    borderWidth: 1,
    borderColor: '#e0cfa9',
  },
  targetMarkerReady: {
    backgroundColor: '#e6efe1',
    borderColor: '#79a466',
  },
  north: { top: 35 },
  east: { right: 18, top: 109 },
  south: { bottom: 15 },
  west: { left: 18, top: 109 },
  qiblaArrow: {
    alignItems: 'center',
    justifyContent: 'center',
  },
  centerMark: {
    position: 'absolute',
    width: 48,
    height: 48,
    borderRadius: 24,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#7c5c1e',
    borderWidth: 1,
    borderColor: '#bfa76f',
  },
  bearing: {
    color: '#7c5c1e',
    fontSize: 38,
    fontWeight: '700',
  },
  bearingCaption: {
    color: '#9b8966',
    fontSize: 14,
    marginTop: 3,
  },
  metricsRow: {
    width: '100%',
    minHeight: 86,
    flexDirection: 'row-reverse',
    alignItems: 'center',
    justifyContent: 'space-around',
    marginTop: 24,
    paddingVertical: 12,
    borderTopWidth: 1,
    borderBottomWidth: 1,
    borderColor: '#e0cfa9',
  },
  metric: {
    flex: 1,
    alignItems: 'center',
  },
  metricDivider: {
    width: 1,
    height: 44,
    backgroundColor: '#e0cfa9',
  },
  metricLabel: {
    color: '#9b8966',
    fontSize: 12,
    marginTop: 5,
  },
  metricValue: {
    color: '#7c5c1e',
    fontSize: 13,
    fontWeight: '600',
    marginTop: 3,
    textAlign: 'center',
  },
  calibrationNotice: {
    width: '100%',
    flexDirection: 'row-reverse',
    alignItems: 'flex-start',
    gap: 9,
    marginTop: 18,
    padding: 13,
    borderLeftWidth: 3,
    borderLeftColor: '#bfa76f',
    backgroundColor: '#f3ead7',
  },
  calibrationText: {
    flex: 1,
    color: '#7c5c1e',
    fontSize: 13,
    lineHeight: 20,
    textAlign: 'right',
  },
  locationText: {
    color: '#9b8966',
    fontSize: 12,
    marginTop: 22,
  },
  sourceText: {
    color: '#9b8966',
    fontSize: 12,
    marginTop: 7,
    textAlign: 'center',
  },
  primaryButton: {
    minHeight: 48,
    flexDirection: 'row-reverse',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    marginTop: 22,
    paddingHorizontal: 20,
    borderRadius: 8,
    backgroundColor: '#7c5c1e',
  },
  primaryButtonText: {
    color: '#fff9ef',
    fontSize: 16,
    fontWeight: '700',
  },
});

export default qiblaStyles;
