import { StyleSheet, Platform, Dimensions } from 'react-native';

const { width: screenWidth, height: screenHeight } = Dimensions.get('window');

const searchScreenStyles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: '#fdf6ec',
  },
  keyboardView: {
    flex: 1,
  },
  scrollContainer: {
    flexGrow: 1,
  },
  container: {
    flex: 1,
    paddingHorizontal: 0,
    minHeight: screenHeight,
  },
  card: {
    backgroundColor: 'transparent',
    paddingTop: 0,
    paddingBottom: 16,
    paddingHorizontal: 20,
    width: '100%',
    flex: 1,
  },
  header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 20,
    paddingVertical: 12,
    backgroundColor: 'rgba(255, 249, 239, 0.8)',
    borderBottomWidth: 1,
    borderBottomColor: '#e0cfa9',
  },
  title: {
    fontSize: 24,
    fontWeight: 'bold',
    color: '#7c5c1e',
    textAlign: 'center',
    fontFamily: Platform.OS === 'ios' ? 'Cochin' : 'serif',
    letterSpacing: 0.5,
    flex: 1,
  },
  clearButton: {
    width: 40,
    height: 40,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 20,
    backgroundColor: 'rgba(191, 167, 111, 0.1)',
  },
  backButton: {
    width: 40,
    height: 40,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 20,
    backgroundColor: 'rgba(191, 167, 111, 0.1)',
  },
  toggleContainer: {
    flexDirection: 'row',
    backgroundColor: '#f8ecd4',
    borderRadius: 16,
    padding: 4,
    marginBottom: 20,
    marginHorizontal: 0,
  },
  toggleButton: {
    flex: 1,
    paddingVertical: 10,
    paddingHorizontal: 12,
    borderRadius: 12,
    alignItems: 'center',
  },
  toggleButtonActive: {
    backgroundColor: '#7c5c1e',
    shadowColor: '#7c5c1e',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.3,
    shadowRadius: 4,
    elevation: 3,
  },
  toggleButtonText: {
    fontSize: 14,
    color: '#7c5c1e',
    fontWeight: '600',
    fontFamily: Platform.OS === 'ios' ? 'Cochin' : 'serif',
  },
  toggleButtonTextActive: {
    color: '#ffffff',
  },
  fieldGroup: {
    width: '100%',
    marginBottom: 20,
  },
  label: {
    fontSize: 16,
    color: '#7c5c1e',
    alignSelf: 'flex-end',
    marginBottom: 8,
    fontFamily: Platform.OS === 'ios' ? 'Cochin' : 'serif',
    fontWeight: '600',
  },
  input: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: '#ffffff',
    borderRadius: 16,
    borderWidth: 2,
    borderColor: '#e0cfa9',
    paddingVertical: Platform.OS === 'ios' ? 14 : 12,
    paddingHorizontal: 16,
    shadowColor: '#bfa76f',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 2,
  },
  textInput: {
    backgroundColor: '#ffffff',
    borderRadius: 16,
    borderWidth: 2,
    borderColor: '#e0cfa9',
    paddingVertical: Platform.OS === 'ios' ? 14 : 12,
    paddingHorizontal: 16,
    fontSize: 16,
    color: '#2c2c2c',
    fontFamily: Platform.OS === 'ios' ? 'Cochin' : 'serif',
    textAlign: 'right',
    shadowColor: '#bfa76f',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 2,
    minHeight: 50,
  },
  searchHint: {
    fontSize: 12,
    color: '#bfa76f',
    textAlign: 'right',
    marginTop: 6,
    fontFamily: Platform.OS === 'ios' ? 'Cochin' : 'serif',
    fontStyle: 'italic',
  },
  inputDisabled: {
    backgroundColor: '#f8ecd4',
    color: '#bfa76f',
    borderColor: '#e0cfa9',
    opacity: 0.7,
  },
  button: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#7c5c1e',
    paddingVertical: 16,
    paddingHorizontal: 32,
    borderRadius: 24,
    marginVertical: 16,
    shadowColor: '#7c5c1e',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 6,
    minWidth: 140,
  },
  buttonDisabled: {
    backgroundColor: '#bfa76f',
    opacity: 0.6,
  },
  buttonIcon: {
    marginLeft: 8,
  },
  buttonText: {
    color: '#ffffff',
    fontSize: 18,
    fontWeight: 'bold',
    fontFamily: Platform.OS === 'ios' ? 'Cochin' : 'serif',
  },
  errorContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#fff0f0',
    borderColor: '#ffcccb',
    borderWidth: 1,
    borderRadius: 12,
    padding: 12,
    marginTop: 8,
  },
  error: {
    color: '#b53a3a',
    fontSize: 14,
    textAlign: 'right',
    fontFamily: Platform.OS === 'ios' ? 'Cochin' : 'serif',
    marginLeft: 8,
    flex: 1,
  },
  resultsContainer: {
    marginTop: 20,
  },
  resultsHeader: {
    fontSize: 18,
    color: '#7c5c1e',
    fontWeight: 'bold',
    textAlign: 'center',
    marginBottom: 16,
    fontFamily: Platform.OS === 'ios' ? 'Cochin' : 'serif',
  },
  moreResultsText: {
    fontSize: 14,
    color: '#bfa76f',
    textAlign: 'center',
    marginTop: 12,
    fontFamily: Platform.OS === 'ios' ? 'Cochin' : 'serif',
    fontStyle: 'italic',
  },
  resultCard: {
    backgroundColor: 'rgba(255, 255, 255, 0.95)',
    borderRadius: 16,
    borderWidth: 1,
    borderColor: '#e0cfa9',
    padding: 20,
    marginTop: 16,
    marginBottom: 8,
    marginHorizontal: 0,
    width: '100%',
    shadowColor: '#bfa76f',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.12,
    shadowRadius: 8,
    elevation: 4,
  },
  resultHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 16,
    paddingBottom: 12,
    borderBottomWidth: 1,
    borderBottomColor: '#f8ecd4',
  },
  resultSurah: {
    fontSize: 16,
    color: '#7c5c1e',
    fontFamily: Platform.OS === 'ios' ? 'Cochin' : 'serif',
    fontWeight: '600',
    flex: 1,
    textAlign: 'right',
  },
  resultNumber: {
    backgroundColor: '#7c5c1e',
    borderRadius: 16,
    paddingHorizontal: 12,
    paddingVertical: 6,
    marginLeft: 12,
  },
  resultNumberText: {
    color: '#ffffff',
    fontSize: 14,
    fontWeight: 'bold',
  },
  ayahContainer: {
    backgroundColor: '#fdf6ec',
    borderRadius: 16,
    padding: 16,
    marginBottom: 12,
  },
  resultAyah: {
    fontSize: 20,
    color: '#2c2c2c',
    fontFamily: 'Uthmani',
    textAlign: 'right',
    lineHeight: 32,
    letterSpacing: 0.5,
  },
  tafsirContainer: {
    backgroundColor: '#f8ecd4',
    borderRadius: 12,
    padding: 12,
  },
  tafsirLabel: {
    fontSize: 14,
    color: '#7c5c1e',
    fontWeight: 'bold',
    marginBottom: 6,
    textAlign: 'right',
    fontFamily: Platform.OS === 'ios' ? 'Cochin' : 'serif',
  },
  resultTafsir: {
    fontSize: 14,
    color: '#5d4a1a',
    fontFamily: Platform.OS === 'ios' ? 'Cochin' : 'serif',
    textAlign: 'right',
    lineHeight: 22,
  },
  shareButton: {
    flexDirection: 'row',
    alignItems: 'center',
    alignSelf: 'center',
    marginTop: 18,
    backgroundColor: '#f8ecd4',
    borderRadius: 18,
    paddingVertical: 10,
    paddingHorizontal: 24,
    borderWidth: 1.5,
    borderColor: '#bfa76f',
    shadowColor: '#bfa76f',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.12,
    shadowRadius: 4,
    elevation: 2,
  },
  shareButtonText: {
    color: '#7c5c1e',
    fontSize: 16,
    fontWeight: 'bold',
    fontFamily: Platform.OS === 'ios' ? 'Cochin' : 'serif',
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.18)',
  },
  selectionModal: {
    position: 'absolute',
    top: 60,
    left: 18,
    right: 18,
    bottom: 40,
    backgroundColor: '#fff9ef',
    borderRadius: 24,
    borderWidth: 2,
    borderColor: '#e0cfa9',
    shadowColor: '#bfa76f',
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.18,
    shadowRadius: 18,
    elevation: 20,
    padding: 0,
    zIndex: 2000,
    overflow: 'hidden',
  },
  modalHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 18,
    paddingTop: 18,
    paddingBottom: 8,
    borderBottomWidth: 1,
    borderBottomColor: '#f8ecd4',
    backgroundColor: 'transparent',
  },
  modalTitle: {
    fontSize: 20,
    color: '#7c5c1e',
    fontWeight: 'bold',
    fontFamily: Platform.OS === 'ios' ? 'Cochin' : 'serif',
    flex: 1,
    textAlign: 'center',
  },
  modalCloseBtn: {
    padding: 6,
    borderRadius: 16,
    backgroundColor: 'rgba(191, 167, 111, 0.08)',
  },
  modalBackBtn: {
    padding: 6,
    borderRadius: 16,
    backgroundColor: 'rgba(191, 167, 111, 0.08)',
    marginRight: 8,
  },
  modalSearchInput: {
    backgroundColor: '#fff',
    borderRadius: 14,
    borderWidth: 1.5,
    borderColor: '#e0cfa9',
    paddingVertical: 12,
    paddingHorizontal: 16,
    fontSize: 16,
    color: '#2c2c2c',
    fontFamily: Platform.OS === 'ios' ? 'Cochin' : 'serif',
    textAlign: 'right',
    margin: 18,
    marginBottom: 0,
  },
  modalSurahList: {
    flex: 1,
    marginTop: 8,
  },
  modalSurahItem: {
    flexDirection: 'row-reverse',
    alignItems: 'center',
    paddingVertical: 14,
    paddingHorizontal: 18,
    borderBottomWidth: 1,
    borderBottomColor: '#f8ecd4',
  },
  modalSurahNum: {
    fontSize: 15,
    color: '#fff',
    backgroundColor: '#bfa76f',
    borderRadius: 12,
    paddingHorizontal: 10,
    paddingVertical: 4,
    minWidth: 32,
    textAlign: 'center',
    marginLeft: 12,
    fontWeight: 'bold',
  },
  modalSurahTextContainer: {
    flex: 1,
  },
  modalSurahName: {
    fontSize: 16,
    color: '#2c2c2c',
    textAlign: 'right',
    fontFamily: Platform.OS === 'ios' ? 'Cochin' : 'serif',
    fontWeight: '600',
  },
  modalSurahEnglish: {
    fontSize: 13,
    color: '#7c5c1e',
    textAlign: 'right',
    fontFamily: Platform.OS === 'ios' ? 'Cochin' : 'serif',
    opacity: 0.8,
    marginTop: 2,
  },
  modalAyahList: {
    flex: 1,
    marginTop: 8,
  },
  modalAyahItem: {
    paddingVertical: 14,
    paddingHorizontal: 24,
    borderBottomWidth: 1,
    borderBottomColor: '#f8ecd4',
    alignItems: 'flex-end',
  },
  modalAyahRow: {
    flexDirection: 'row-reverse',
    alignItems: 'center',
  },
  modalAyahNum: {
    fontSize: 16,
    color: '#fff',
    backgroundColor: '#bfa76f',
    borderRadius: 12,
    paddingHorizontal: 10,
    paddingVertical: 4,
    minWidth: 32,
    textAlign: 'center',
    marginLeft: 12,
    fontWeight: 'bold',
  },
  modalAyahText: {
    fontSize: 18,
    color: '#2c2c2c',
    fontFamily: 'Uthmani',
    textAlign: 'right',
    flex: 1,
    lineHeight: 32,
  },
  actionButtonsContainer: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: 18,
    gap: 12,
  },
  actionButton: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#f8ecd4',
    borderRadius: 18,
    paddingVertical: 10,
    paddingHorizontal: 20,
    borderWidth: 1.5,
    borderColor: '#bfa76f',
    shadowColor: '#bfa76f',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.12,
    shadowRadius: 4,
    elevation: 2,
    minWidth: 100,
    justifyContent: 'center',
  },
  actionButtonText: {
    color: '#7c5c1e',
    fontSize: 15,
    fontWeight: 'bold',
    fontFamily: Platform.OS === 'ios' ? 'Cochin' : 'serif',
  },
});

export default searchScreenStyles; 