import { StyleSheet } from 'react-native';

const surahListStyles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: '#fdf6ec',
  },
  loadingContainer: {
    flex: 1,
    backgroundColor: '#fdf6ec',
    justifyContent: 'center',
    alignItems: 'center',
  },
  loadingContent: {
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 40,
  },
  loadingText: {
    marginTop: 20,
    fontSize: 18,
    color: '#7c5c1e',
    fontFamily: 'Cochin',
    fontWeight: 'bold',
    textAlign: 'center',
  },
  pageBackground: {
    flex: 1,
    backgroundColor: '#fdf6ec',
    paddingTop: 0,
    paddingBottom: 12,
  },
  fullWidthBanner: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: 'rgba(255, 249, 239, 0.8)',
    borderBottomWidth: 1,
    borderBottomColor: '#e0cfa9',
    marginTop: 0,
    marginBottom: 16,
    marginStart: 0,
    marginEnd: 0,
    paddingVertical: 12,
    paddingHorizontal: 20,
  },
  fullWidthBackButton: {
    padding: 8,
    borderRadius: 20,
    backgroundColor: 'rgba(191, 167, 111, 0.1)',
  },
  fullWidthSurahNameContainer: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
  },
  surahNameHeader: {
    fontSize: 24,
    color: '#7c5c1e',
    fontWeight: 'bold',
    fontFamily: 'Cochin',
    letterSpacing: 0.5,
    textAlign: 'center',
  },
  listContent: {
    paddingHorizontal: '3%',
    paddingBottom: 30,
    paddingTop: 10,
    flexGrow: 1,
  },
  surahCard: {
    backgroundColor: '#fff9ef',
    borderRadius: 18,
    borderWidth: 2,
    borderColor: '#e0cfa9',
    paddingVertical: 18,
    paddingHorizontal: '5%',
    marginHorizontal: 0,
    marginBottom: 14,
    shadowColor: '#bfa76f',
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.13,
    shadowRadius: 12,
    elevation: 6,
    position: 'relative',
    width: '100%',
    maxWidth: 500,
    alignSelf: 'center',
  },
  surahCardLoading: {
    opacity: 0.7,
  },
  cardRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    flexWrap: 'wrap',
  },
  englishName: {
    fontSize: 16,
    color: '#7c5c1e',
    fontWeight: '500',
    opacity: 0.85,
    flex: 1,
    textAlign: 'left',
    fontFamily: 'Cochin',
    minWidth: 120,
  },
  arabicName: {
    fontSize: 20,
    color: '#7c5c1e',
    fontWeight: 'bold',
    fontFamily: 'Cochin',
    letterSpacing: 1,
    flex: 1,
    textAlign: 'right',
    minWidth: 120,
  },
  backArrow: {
    fontSize: 24,
    color: '#7c5c1e',
    fontWeight: 'bold',
    marginRight: 12,
  },
  searchBar: {
    backgroundColor: '#fff9ef',
    borderRadius: 14,
    borderWidth: 1.5,
    borderColor: '#e0cfa9',
    paddingVertical: 10,
    paddingHorizontal: 18,
    fontSize: 18,
    color: '#7c5c1e',
    marginHorizontal: 16,
    marginBottom: 12,
    marginTop: 2,
    fontFamily: 'Cochin',
    textAlign: 'right',
  },
  loadingOverlay: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: 'rgba(248, 236, 212, 0.9)',
    borderRadius: 18,
    justifyContent: 'center',
    alignItems: 'center',
    flexDirection: 'row',
  },
  scrollToTopButton: {
    position: 'absolute',
    bottom: 30,
    right: 20,
    width: 50,
    height: 50,
    borderRadius: 25,
    backgroundColor: '#7c5c1e',
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 8,
    borderWidth: 2,
    borderColor: '#bfa76f',
  },
  scrollToTopArrow: {
    fontSize: 24,
    color: '#fdf6ec',
    fontWeight: 'bold',
  },
  modeButton: {
    flex: 1,
    paddingVertical: 10,
    marginHorizontal: 8,
    backgroundColor: '#f8ecd4',
    borderRadius: 10,
    borderWidth: 1.5,
    borderColor: '#bfa76f',
    alignItems: 'center',
  },
  modeButtonActive: {
    backgroundColor: '#bfa76f',
  },
  modeButtonText: {
    fontSize: 18,
    color: '#7c5c1e',
    fontWeight: 'bold',
  },
  modeButtonTextActive: {
    color: '#fff',
  },
  tafsirAyahCard: {
    backgroundColor: '#fff9ef',
    borderRadius: 14,
    borderWidth: 1.5,
    borderColor: '#e0cfa9',
    padding: 16,
    marginBottom: 12,
    marginHorizontal: 6,
    shadowColor: '#bfa76f',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.10,
    shadowRadius: 6,
    elevation: 2,
  },
  tafsirText: {
    color: '#7c5c1e',
    fontSize: 16,
    marginTop: 8,
    fontFamily: 'Cochin',
  },
  tafsirTextEmpty: {
    color: '#bfa76f',
    fontSize: 15,
    marginTop: 8,
    fontStyle: 'italic',
    fontFamily: 'Cochin',
  },
  ayahText: {
    color: '#2c2c2c',
    fontSize: 24,
    lineHeight: 40,
    fontFamily: 'Uthmani',
    textAlign: 'right',
  },
  scrollContainer: {
    flex: 1,
  },
  scrollContent: {
    paddingBottom: 20,
  },
  ayahFrame: {
    backgroundColor: '#fff9ef',
    borderRadius: 18,
    borderWidth: 2,
    borderColor: '#e0cfa9',
    padding: 20,
    marginHorizontal: 16,
    shadowColor: '#bfa76f',
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.13,
    shadowRadius: 12,
    elevation: 6,
  },
  ayahNumber: {
    color: '#bfa76f',
    fontSize: 20,
    fontWeight: 'bold',
  },
  ayahNumberInner: {
    fontSize: 18,
  },
  ayahSeparator: {
    fontSize: 24,
  },
  paginationContainer: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 24,
    paddingVertical: 16,
    backgroundColor: '#fdf6ec',
    borderTopWidth: 1,
    borderTopColor: '#e0cfa9',
  },
  arrowButton: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: '#f8ecd4',
    borderColor: '#bfa76f',
    borderWidth: 1,
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#bfa76f',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 2,
  },
  arrowButtonDisabled: {
    backgroundColor: '#f0f0f0',
    borderColor: '#ccc',
  },
  arrowText: {
    color: '#7c5c1e',
    fontSize: 30,
    fontWeight: 'bold',
    marginTop: -13,
  },
  arrowTextDisabled: {
    color: '#999',
  },
  pageInfoContainer: {
    alignItems: 'center',
  },
  pageInfoText: {
    color: '#7c5c1e',
    fontSize: 16,
    fontWeight: 'bold',
    fontFamily: 'Cochin',
  },
});

export default surahListStyles; 