import { StyleSheet } from 'react-native';

const surahScreenStyles = StyleSheet.create({
  container: {
    flex: 1,
  },
  loading: {
    flex: 1,
    textAlign: 'center',
    marginTop: 50,
    fontSize: 18,
    color: '#666',
  },
  pageBackground: {
    flex: 1,
    backgroundColor: '#fdf6ec',
    paddingTop: 24,
    paddingBottom: 12,
  },
  surahBanner: {
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#f8ecd4',
    borderColor: '#bfa76f',
    borderWidth: 2,
    borderRadius: 12,
    marginHorizontal: 24,
    marginBottom: 18,
    paddingVertical: 6,
    paddingHorizontal: 24,
    shadowColor: '#bfa76f',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.15,
    shadowRadius: 6,
    elevation: 3,
  },
  surahName: {
    fontSize: 24,
    color: '#7c5c1e',
    fontWeight: 'bold',
    fontFamily: 'Cochin',
    letterSpacing: 1,
    textAlign: 'center',
  },
  pageIndicator: {
    fontSize: 14,
    color: '#7c5c1e',
    marginTop: 4,
    opacity: 0.8,
  },
  scrollContainer: {
    flex: 1,
  },
  scrollContent: {
    paddingBottom: 20,
  },
  ayahFrame: {
    backgroundColor: '#fff9ef',
    borderRadius: 18,
    borderWidth: 2,
    borderColor: '#e0cfa9',
    padding: 20,
    marginHorizontal: 16,
    shadowColor: '#bfa76f',
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.13,
    shadowRadius: 12,
    elevation: 6,
  },
  paragraphText: {
    textAlign: 'right',
    lineHeight: 40,
    fontSize: 24,
    fontFamily: 'UthmaniFull',
  },
  ayahText: {
    color: '#2c2c2c',
    fontSize: 24,
    lineHeight: 40,
    fontFamily: 'UthmaniFull',
  },
  ayahNumber: {
    color: '#bfa76f',
    fontSize: 20,
    fontWeight: 'bold',
  },
  ayahNumberInner: {
    fontSize: 18,
  },
  ayahSeparator: {
    fontSize: 24,
  },
  paginationContainer: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 24,
    paddingVertical: 16,
    backgroundColor: '#fdf6ec',
    borderTopWidth: 1,
    borderTopColor: '#e0cfa9',
  },
  arrowButton: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: '#f8ecd4',
    borderColor: '#bfa76f',
    borderWidth: 1,
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#bfa76f',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 2,
  },
  arrowButtonDisabled: {
    backgroundColor: '#f0f0f0',
    borderColor: '#ccc',
  },
  arrowText: {
    color: '#7c5c1e',
    fontSize: 30,
    fontWeight: 'bold',
    marginTop: -13,
  },
  arrowTextDisabled: {
    color: '#999',
  },
  pageInfoContainer: {
    alignItems: 'center',
  },
  pageInfoText: {
    color: '#7c5c1e',
    fontSize: 16,
    fontWeight: 'bold',
    fontFamily: 'Cochin',
  },
  basmalaContainer: {
    alignItems: 'center',
    marginVertical: 18,
  },
  basmalaImage: {
    width: '80%',
    height: 40,
    maxWidth: 400,
  },
  customHeader: {
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 30,
    marginBottom: 16,
    paddingHorizontal: 16,
  },
  backButton: {
    // Removed - no longer needed
  },
  backArrow: {
    fontSize: 28,
    color: '#7c5c1e',
    fontWeight: 'bold',
    marginRight: 12,
    marginTop: -9,
  },
  surahBannerHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#f8ecd4',
    borderColor: '#bfa76f',
    borderWidth: 2,
    borderRadius: 16,
    paddingVertical: 8,
    paddingHorizontal: 24,
    shadowColor: '#bfa76f',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.15,
    shadowRadius: 6,
    elevation: 3,
  },
  surahNameHeader: {
    fontSize: 24,
    color: '#7c5c1e',
    fontWeight: 'bold',
    fontFamily: 'Cochin',
    letterSpacing: 1,
    textAlign: 'center',
  },
  fullWidthBanner: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#f8ecd4',
    borderColor: '#bfa76f',
    borderWidth: 2,
    borderRadius: 16,
    marginTop: -15,
    marginBottom: 16,
    marginStart: 10,
    marginEnd: 10,
    paddingVertical: 8,
    shadowColor: '#bfa76f',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.15,
    shadowRadius: 6,
    elevation: 3,
  },
  fullWidthBackButton: {
    position: 'absolute',
    left: 16,
    zIndex: 2,
    padding: 8,
    marginTop: -9,
  },
  fullWidthSurahNameContainer: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
  },
});

export default surahScreenStyles; 