import { StyleSheet, Dimensions } from 'react-native';

const { width } = Dimensions.get('window');

const tasbeehScreenStyles = StyleSheet.create({
  safeArea: {
    flex: 1,
  },
  scrollContent: {
    flexGrow: 1,
    paddingBottom: 30,
  },
  header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 20,
    paddingVertical: 15,
    backgroundColor: 'rgba(255,249,239,0.95)',
    borderBottomWidth: 2,
    borderBottomColor: '#bfa76f',
  },
  backButton: {
    width: 40,
    height: 40,
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 20,
    backgroundColor: 'rgba(191,167,111,0.15)',
  },
  headerTitle: {
    fontSize: 24,
    fontWeight: 'bold',
    color: '#7c5c1e',
    fontFamily: 'Cochin',
    letterSpacing: 1,
  },
  dhikrContainer: {
    marginHorizontal: 20,
    marginTop: 20,
    marginBottom: 10,
  },
  dhikrButton: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    backgroundColor: 'rgba(255,249,239,0.98)',
    borderRadius: 16,
    borderWidth: 2,
    borderColor: '#bfa76f',
    paddingVertical: 20,
    paddingHorizontal: 20,
    shadowColor: '#bfa76f',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.15,
    shadowRadius: 8,
    elevation: 5,
  },
  dhikrText: {
    fontSize: 20,
    color: '#7c5c1e',
    fontWeight: '600',
    flex: 1,
    textAlign: 'center',
    marginRight: 10,
  },
  dhikrListContainer: {
    marginHorizontal: 20,
    marginBottom: 15,
    backgroundColor: 'rgba(255,249,239,0.98)',
    borderRadius: 16,
    borderWidth: 2,
    borderColor: '#bfa76f',
    padding: 15,
    maxHeight: 300,
    shadowColor: '#bfa76f',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.15,
    shadowRadius: 8,
    elevation: 5,
  },
  dhikrListTitle: {
    fontSize: 18,
    color: '#7c5c1e',
    fontWeight: 'bold',
    marginBottom: 10,
    textAlign: 'center',
    fontFamily: 'Cochin',
  },
  dhikrList: {
    maxHeight: 250,
  },
  dhikrListItem: {
    backgroundColor: 'rgba(224,207,169,0.2)',
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#bfa76f',
    paddingVertical: 15,
    paddingHorizontal: 15,
    marginBottom: 8,
  },
  dhikrListItemText: {
    fontSize: 16,
    color: '#7c5c1e',
    textAlign: 'center',
    fontWeight: '500',
  },
  tasbeehContainer: {
    alignItems: 'center',
    marginTop: 10,
    paddingHorizontal: 20,
  },
  tasbeehImageContainer: {
    width: width * 0.8,
    aspectRatio: 1,
    alignSelf: 'center',
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: 20,
    position: 'relative',
  },
  tasbeehImage: {
    width: '100%',
    height: '100%',
  },
  displayOverlay: {
    position: 'absolute',
    top: '20%',
    left: '50%',
    transform: [{ translateX: -80 }],
    width: 160,
    height: 60,
    justifyContent: 'center',
    alignItems: 'center',
  },
  displayNumber: {
    fontSize: 42,
    fontWeight: 'bold',
    color: '#2a3a2a',
    fontFamily: 'Courier New',
    textShadowColor: 'rgba(0,0,0,0.3)',
    textShadowOffset: { width: 1, height: 1 },
    textShadowRadius: 2,
  },
  countButtonOverlay: {
    position: 'absolute',
    bottom: '15%',
    left: '40%',
    width: 60,
    height: 60,
    borderRadius: 50,
  },
  countButton: {
    width: '100%',
    height: '100%',
    borderRadius: 50,
  },
  resetButtonOverlay: {
    position: 'absolute',
    bottom: '38%',
    right: '25%',
    width: 20,
    height: 20,
    borderRadius: 22.5,
    backgroundColor: 'transparent',
  },
  historyContainer: {
    marginHorizontal: 20,
    marginTop: 25,
    marginBottom: 20,
    backgroundColor: 'rgba(255,249,239,0.98)',
    borderRadius: 20,
    borderWidth: 3,
    borderColor: '#bfa76f',
    padding: 20,
    shadowColor: '#bfa76f',
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.2,
    shadowRadius: 12,
    elevation: 8,
  },
  historyTitle: {
    fontSize: 22,
    color: '#7c5c1e',
    fontWeight: 'bold',
    marginBottom: 15,
    textAlign: 'center',
    fontFamily: 'Cochin',
    letterSpacing: 1,
  },
  historyItem: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    backgroundColor: 'rgba(224,207,169,0.25)',
    borderRadius: 12,
    borderWidth: 2,
    borderColor: '#bfa76f',
    paddingVertical: 15,
    paddingHorizontal: 18,
    marginBottom: 10,
  },
  historyDhikr: {
    fontSize: 18,
    color: '#7c5c1e',
    fontWeight: '600',
    flex: 1,
    marginRight: 10,
    fontFamily: 'Cochin',
  },
  historyCountBadge: {
    backgroundColor: '#bfa76f',
    borderRadius: 20,
    paddingVertical: 8,
    paddingHorizontal: 16,
    minWidth: 50,
    alignItems: 'center',
    borderWidth: 2,
    borderColor: '#7c5c1e',
    shadowColor: '#7c5c1e',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.3,
    shadowRadius: 4,
    elevation: 4,
  },
  historyCount: {
    fontSize: 20,
    color: '#fff',
    fontWeight: 'bold',
    fontFamily: 'Cochin',
  },
});

export default tasbeehScreenStyles;
